# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iHonour' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for iHonour
 
    pod 'Masonry'
  
    pod 'YYKit', '~> 1.0.9'

    #pod 'YYWebImage'
    #pod 'YYImage'

    # 集成新浪微博 + 微信 + QQ
    pod 'UMengUShare/UI'
    pod 'UMengUShare/Social/Sina'
    pod 'UMengUShare/Social/WeChat'
    pod 'UMengUShare/Social/QQ'
    pod 'UMengAnalytics'

end
