# Uncomment this line to define a global platform for your project
# source 'https://github.com/CocoaPods/Specs.git'
platform :ios, ‘9.0’
inhibit_all_warnings!
use_frameworks!

target 'iTVshows' do

  pod 'Alamofire', '~> 4.0.0'
  pod 'SwiftyJSON', '~> 3.1.1'
  
#  pod 'YYKit', '~> 1.0.9'

   pod 'YYWebImage'
   pod 'YYImage'


end
